resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: CorysBashCalcRepo 
    type: github
    endpoint: CorysGitHub
    name: CoryJ34/bashCalc
  # The name used to reference this repository in the checkout step
  - repository: CorysWindowsBatchRepo
    type: github
    endpoint: CorysGitHub
    name: CoryJ34/winBatch

trigger:
- master

stages:
- stage: UbuntuQAEnvCheck
  jobs:
  - job: InlineScripts
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: none
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
