
trigger:
- master

#Muliple Stages with multiple jobs
#Different OS and different github repo
stages:

#First Stage on Ubuntu
- stage: UbuntuQAEnvCheck
  jobs:
  - job: InlineScripts
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    #No Checkout
    - checkout: none
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Learning is fun, please check below.
        echo See https://www.kavinschool.com/content/
      displayName: 'Run a multi-line script'

#Second Stage on Ubuntu Prod
- stage: UbuntuProdEnvCheck
  dependsOn: UbuntuQAEnvCheck
  condition: succeeded()
  jobs:
  - job: ExternalScripts
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: git@github.com:kpassoubady/winBatch.git
      - task: Bash@3
        displayName: 'install bc'
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo 'installation starts'
            sudo apt-get install bc
            echo 'installation ends'

      - task: Bash@3
        displayName: 'run calc'
        inputs:
          filePath: 'calc.sh'

#Third Stage on Windows QA

- stage: WindowsQAEnvCheck
  dependsOn: UbuntuQAEnvCheck
  condition: succeeded()
  jobs:
  - job: InternalScripts
  #Windows Microsoft hosted image
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: none
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Learning is fun, enquire below.
        echo See https://www.kavinschool.com/content/
      displayName: 'Run a multi-line script'

#Fourth Stage on Windows Prod

- stage: WindowsProdEnvCheck
  dependsOn: UbuntuProdEnvCheck
  condition: succeeded()
  jobs:
  - job: InternalScripts
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: git@github.com:kpassoubady/bashCalc.git
    - task: BatchScript@1
      inputs:
        filename: 'power.bat'
        arguments: '3 4'

    - task: BatchScript@1
      inputs:
        filename: 'calc.bat'
        arguments: '300 100'
        